### ISSUE TITLE
dropout value error

### ISSUE THREAD

**Issue by bflipeed** [BelBES/crnn-pytorch#2]
crnn-pytorch-master python3 train.py --test-init True --test-epoch 10 --output-dir ./snap
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/jing/.torch/models/resnet18-5c106cde.pth
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 46827520/46827520 [00:03<00:00, 12340925.60it/s]
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    main()
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 55, in main
    net = load_model(data.get_abc(), seq_proj, backend, snapshot, cuda)
  File "/Users/jing/Desktop/crnn-pytorch-master/models/model_loader.py", line 16, in load_model
    net = CRNN(abc=abc, seq_proj=seq_proj, backend=backend)
  File "/Users/jing/Desktop/crnn-pytorch-master/models/crnn.py", line 43, in __init__
    dropout=rnn_dropout, bidirectional=True)
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 485, in __init__
    super(GRU, self).__init__('GRU', *args, **kwargs)
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 31, in __init__
    raise ValueError("dropout should be a number in range [0, 1] "
ValueError: dropout should be a number in range [0, 1] representing the probability of an element being zeroed

**Comment by bflipeed** [comment]
I figure it out and change the default rnn_dropout=false to run_dropout=0
