### ISSUE TITLE
About default training with test dataset generator 

### ISSUE THREAD

**Issue by bflipeed** [BelBES/crnn-pytorch#3]
when I use test dataset generator, I think I should return some training data, but how can I use is for train, cause in train.py I found that you use generated data with method "set_mode" which doesn't have definition in test_data.py
here is error report:
(dip) crnn-pytorch-master python3 train.py --test-init True --test-epoch 10 --output-dir ./snap
testdata
Test phase
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    main()
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jing/anaconda3/envs/dip/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 83, in main
    data.set_mode('test')
TypeError: set_mode() takes 1 positional argument but 2 were given

**Comment by BelBES** [comment]
Error was fixed
