### ISSUE TITLE
Attribute error due to test dataset.py

### ISSUE THREAD

**Issue by BobbleHeadAlien** [BelBES/crnn-pytorch#5]
`AttributeError: Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/new/Kaushik/crnn-pytorch/dataset/test_data.py", line 64, in __getitem__
    sample = {"img": img, "seq": seq, "seq_len": len(seq), "aug": self.mode == "train"}
AttributeError: 'TestDataset' object has no attribute 'mode'
`

This is the error im getting when im running the commands given in the read me. Before this i got an error saying the dropout should be a number between [0,1] in the crnn.py file. where the default value was set to False. I changed it and i got this error. Please help.

**Comment by BelBES** [comment]
The issue was fixed. Please rebase to upstream
